%% Do not edit this file
%% closing open figures and clearing workspace

close all;
clear all;

%% parameters

sz = [50 25 10];                % max spacial size of the superpixel
diff = 0.2;                     % max difference in the intensity domain
err_flag = 0;                   % 0 - no errrors

%% loading image

im = imread('superpix.jpg');
im = im2double(im);

%% Compute superpixels

[spix1] = superpixel(rgb2gray(im),sz(1),diff);
[spix2] = superpixel(rgb2gray(im),sz(2),diff);
[spix3] = superpixel(rgb2gray(im),sz(3),diff);

%% output data check

if(strcmp(class(spix1),'double'))
	num = max(spix1(:));
    temp = {};
    for i = 1:num temp{i} = find(spix1 == i); end
    spix1 = temp;
    
    num = max(spix2(:));
    temp = {};
    for i = 1:num temp{i} = find(spix2 == i); end
    spix2 = temp;
    
    num = max(spix3(:));
    temp = {};
    for i = 1:num temp{i} = find(spix3 == i); end
    spix3 = temp;
    
    display('format of the output is correct');
    display('transormation finished');
    err_flag = 0;

elseif(strcmp(class(spix1),'cell'))
    display('format of the output is correct');
    err_flag = 0;
else
    display('Error: output is incorrect');
    err_flag = 1;
end

%% visualisation

if(err_flag == 0)

figure;
subplot 221; imshow(im); title('Original image');
subplot 222; imshow(im); title('Boundaries of the superpixels');
hold on;

[si,sj,~] = size(im);

for i = 1:numel(spix1)
	map = zeros(si,sj);
	map(spix1{i}) = 1;
    [B,~] = bwboundaries(map,'noholes');
	for k = 1:length(B)
        boundary = B{k};
        plot(boundary(:,2), boundary(:,1), 'Color',[0 0 0], 'LineWidth', 1);
	end
end
hold off;
subplot 223; imshow(im); title('Boundaries of the superpixels');
hold on;
for i = 1:numel(spix2)
	map = zeros(si,sj);
	map(spix2{i}) = 1;
    [B,~] = bwboundaries(map,'noholes');
	for k = 1:length(B)
        boundary = B{k};
        plot(boundary(:,2), boundary(:,1), 'Color',[0 0 0], 'LineWidth', 1);
	end
end
hold off;
subplot 224; imshow(im); title('Boundaries of the superpixels');
hold on;
for i = 1:numel(spix3)
	map = zeros(si,sj);
	map(spix3{i}) = 1;
    [B,~] = bwboundaries(map,'noholes');
	for k = 1:length(B)
        boundary = B{k};
        plot(boundary(:,2), boundary(:,1), 'Color',[0 0 0], 'LineWidth', 1);
	end
end
hold off;

end
